version: '3'

services:
  youtube-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - WHISPER_MODEL=base
      - FLASK_ENV=production
    volumes:
      - ./temp:/app/temp
    restart: unless-stopped
